#include "parser.h"
#include <sstream>
static std::string posmsg(const Token&t){return " at position "+std::to_string(t.pos);}
bool Parser::at(TokenType t) const{return current().type==t;} const Token& Parser::current() const{return tokens.at(pos);}
std::shared_ptr<ASTNode> Parser::parse(){auto r=parseUnion(); if(!at(TokenType::END)) throw ParserError("Unexpected token"+posmsg(current())); return r;}
std::shared_ptr<ASTNode> Parser::parseUnion(){auto n=parseConcat(); while(at(TokenType::UNION)){++pos; auto r=parseConcat(); auto p=std::make_shared<ASTNode>(ASTType::UNION); p->left=n;p->right=r;n=p;} return n;}
std::shared_ptr<ASTNode> Parser::parseConcat(){auto n=parseRepeat(); while(at(TokenType::CONCAT)){++pos; auto r=parseRepeat(); auto p=std::make_shared<ASTNode>(ASTType::CONCAT);p->left=n;p->right=r;n=p;} return n;}
std::shared_ptr<ASTNode> Parser::parseRepeat(){auto n=parseAtom(); if(at(TokenType::STAR)||at(TokenType::PLUS)||at(TokenType::QUESTION)){TokenType t=current().type;++pos; auto p=std::make_shared<ASTNode>(t==TokenType::STAR?ASTType::STAR:t==TokenType::PLUS?ASTType::PLUS:ASTType::OPTIONAL);p->left=n;n=p; if(at(TokenType::STAR)||at(TokenType::PLUS)||at(TokenType::QUESTION)) throw ParserError("Consecutive repetition operators are not allowed at position "+std::to_string(current().pos)+".");} return n;}
std::shared_ptr<ASTNode> Parser::parseAtom(){if(at(TokenType::CHAR)){char c=current().value;++pos;return std::make_shared<ASTNode>(ASTType::SYMBOL,c);} if(at(TokenType::LPAREN)){++pos;if(at(TokenType::RPAREN)) throw ParserError("Empty group is not supported at position "+std::to_string(current().pos)+".");auto n=parseUnion();if(!at(TokenType::RPAREN)) throw ParserError("Unmatched '(' or missing ')' before end of expression.");++pos;return n;} if(at(TokenType::RPAREN)) throw ParserError("Unexpected ')' at position "+std::to_string(current().pos)+"."); if(at(TokenType::STAR)||at(TokenType::PLUS)||at(TokenType::QUESTION)) throw ParserError("Repetition operator '"+std::string(1,current().type==TokenType::STAR?'*':current().type==TokenType::PLUS?'+':'?')+"' has no preceding expression"+posmsg(current())+"."); throw ParserError("Expected a symbol or '('"+posmsg(current())+".");}
