let compiled=null, graphScale=1, replayTimer=null, replaySteps=[], replayIndex=-1, presentation=false;
const $=id=>document.getElementById(id);
const stages={overview:'OVERVIEW',tokens:'LEXER',ast:'PARSER / AST',nfa:'THOMPSON NFA',dfa:'SUBSET DFA',minimized:'MINIMIZATION',testing:'EXECUTION',lab:'TOOLBOX'};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function showStage(id){document.querySelectorAll('.stage').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.stage-btn').forEach(x=>x.classList.toggle('active',x.dataset.stage===id));$('stageTitle').textContent=stages[id]||id.toUpperCase();if(['ast','nfa','dfa','minimized'].includes(id))setTimeout(()=>applyGraphZoom(id),20);window.scrollTo({top:0,behavior:'smooth'});}
function applyGraphZoom(id){const box=$(id+'View'),svg=box?.querySelector('svg');if(svg){svg.style.transform=`scale(${graphScale})`;svg.style.transformOrigin='center center';const z=$(id+'Zoom');if(z)z.textContent=Math.round(graphScale*100)+'%';}}
document.querySelectorAll('.stage-btn').forEach(b=>b.onclick=()=>showStage(b.dataset.stage));
document.querySelectorAll('.next-btn').forEach(b=>b.onclick=()=>showStage(b.dataset.next));
document.querySelectorAll('.flow-node').forEach(b=>b.onclick=()=>showStage(b.dataset.go));
document.querySelectorAll('.lab-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.lab-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.lab-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('lab-'+b.dataset.lab)?.classList.add('active');});
$('compileBtn').onclick=e=>{e.preventDefault();compile()};
$('regex').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();compile()}};
$('regex').oninput=()=>{$('compileStatus').textContent='READY';$('engineText').textContent='ENGINE READY'};
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='enter'){e.preventDefault();compile()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openModal('commandModal');$('commandSearch').focus()}if(e.key>='1'&&e.key<='8'&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA'){showStage(Object.keys(stages)[Number(e.key)-1])}if(e.key==='Escape'){closeModals();if(presentation)togglePresentation()}if(e.code==='Space'&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA'&&document.querySelector('.stage.active')?.id==='testing'){e.preventDefault();testString()}});
async function compile(){const regex=$('regex').value;if(!regex.trim())return showError('Enter a regular expression first.');const btn=$('compileBtn');btn.disabled=true;btn.innerHTML='<span class="compile-dot"></span> BUILDING…';$('compileStatus').textContent='BUILDING';$('engineText').textContent='COMPILING';$('error').classList.add('hidden');try{const t=performance.now();const r=await fetch('/api/compile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({regex})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Compilation failed.');const elapsed=(performance.now()-t).toFixed(1);compiled=d;renderAll(d,elapsed);saveHistory(regex);$('compileStatus').textContent='COMPILED';$('engineText').textContent='ENGINE ONLINE';showStage('overview');}catch(e){compiled=null;$('compileStatus').textContent='ERROR';$('engineText').textContent='BUILD FAILED';showError(e.message)}finally{btn.disabled=false;btn.innerHTML='<span class="compile-dot"></span> BUILD <kbd>Ctrl ↵</kbd>'}}
function showError(m){$('error').textContent=m;$('error').classList.remove('hidden');}
function renderAll(d,elapsed){const s=d.stats;$('sourcePreview').textContent=d.regex;$('tokenCount').textContent=s.tokens;$('nfaStates').textContent=s.nfaStates;$('dfaStates').textContent=s.dfaStates;$('minStates').textContent=s.minimizedStates;$('alphabetSize').textContent=s.alphabet;$('beforeStates').textContent=s.dfaStates;$('afterStates').textContent=s.minimizedStates;$('reduction').textContent=(s.dfaStates?((1-s.minimizedStates/s.dfaStates)*100).toFixed(1):'0.0')+'%';$('buildTime').textContent=`${elapsed} ms · engine ${s.compileTimeMs} ms`;renderTokens(d.tokens);$('astView').innerHTML=astSvg(d.ast);$('nfaView').innerHTML=automataSvg(d.nfa,false);$('dfaView').innerHTML=automataSvg(d.dfa,true);$('minView').innerHTML=automataSvg(d.minimized,false);$('nfaTable').innerHTML=transitionTable(d.nfa.transitions);$('dfaTable').innerHTML=dfaTable(d.dfa);$('minTable').innerHTML=minimizedTable(d.minimized);renderTrace(d.minimizationTrace||[]);bindGraphs();logCompiler([`source: ${d.regex}`,`lexer: ${s.tokens} tokens classified`,`parser: AST generated`,`thompson: ${s.nfaStates} states / ${s.nfaTransitions} transitions`,`subset: ${s.dfaStates} DFA states / ${s.dfaTransitions} transitions`,`optimizer: ${s.minimizedStates} minimal states`,`matcher: ready for execution`,`build: complete in ${s.compileTimeMs} ms`]);resetRun();updateAnalysis();}
function renderTokens(ts){$('tokensView').innerHTML=`<table class="data-table"><thead><tr><th>#</th><th>TYPE</th><th>VALUE</th><th>POSITION</th></tr></thead><tbody>${ts.filter(x=>x.type!=='END').map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.type)}</b></td><td class="mono">${esc(x.value)}</td><td>${x.position}</td></tr>`).join('')}</tbody></table>`}
function isAccepting(d,i){return Array.isArray(d?.accept)?d.accept.includes(i):Number(d?.accept)===i}
function transitionTable(ts){if(!ts?.length)return '<div class="empty">No transitions.</div>';return `<h3>TRANSITION RELATION</h3><table class="data-table"><thead><tr><th>FROM</th><th>SYMBOL</th><th>TO</th></tr></thead><tbody>${ts.map(t=>`<tr><td>q${t.from}</td><td class="mono">${esc(t.symbol)}</td><td>q${t.to}</td></tr>`).join('')}</tbody></table>`}
function dfaTable(d){return `<h3>STATE REPRESENTATION</h3><table class="data-table"><thead><tr><th>STATE</th><th>NFA SUBSET</th><th>ACCEPTING</th></tr></thead><tbody>${d.subsets.map((s,i)=>`<tr><td>q${i}${i===d.start?' · start':''}</td><td class="mono">{${s.join(', ')}}</td><td>${isAccepting(d,i)?'✓':''}</td></tr>`).join('')}</tbody></table>`}
function minimizedTable(d){return `<h3>MINIMIZED STATE GROUPS</h3><table class="data-table"><thead><tr><th>STATE</th><th>ORIGINAL GROUP</th><th>ACCEPTING</th></tr></thead><tbody>${d.subsets.map((s,i)=>`<tr><td>q${i}${i===d.start?' · start':''}</td><td class="mono">{${s.join(', ')}}</td><td>${isAccepting(d,i)?'✓':''}</td></tr>`).join('')}</tbody></table>`}
function renderTrace(trace){$('minTrace').innerHTML=trace.length?trace.map(r=>`<div class="round"><div class="round-title">ROUND ${r.round}${r.round===0?' · INITIAL':''}</div><div class="partition-row">${r.partitions.map((g,i)=>`<div class="partition"><span>P${i}</span><b>{${g.join(', ')}}</b></div>`).join('')}</div></div>`).join(''):'<div class="empty">No minimization trace.</div>'}
function astSvg(root){if(!root)return '<div class="empty">No AST.</div>';const nodes=[],edges=[];let id=0;function walk(n,x,y,parent,depth){if(!n)return;const me=id++;nodes.push({id:me,type:n.type,value:n.value,x,y});if(parent!==null)edges.push({from:parent,to:me});const kids=[n.left,n.right].filter(Boolean);const gap=Math.max(115,220/(depth+1));kids.forEach((k,i)=>walk(k,x+(i-(kids.length-1)/2)*gap,y+82,me,depth+1))}walk(root,0,40,null,0);const minX=Math.min(...nodes.map(n=>n.x)),maxX=Math.max(...nodes.map(n=>n.x));const w=Math.max(820,maxX-minX+180),shift=w/2-(minX+maxX)/2,h=Math.max(330,Math.max(...nodes.map(n=>n.y))+90);const lines=edges.map(e=>{const a=nodes[e.from],b=nodes[e.to];return `<path class="edge" d="M${a.x+shift} ${a.y+26} L${b.x+shift} ${b.y-26}"/>`}).join('');const ns=nodes.map(n=>`<g class="ast-node-wrap" data-node="${n.id}" tabindex="0"><rect class="ast-node" x="${n.x+shift-50}" y="${n.y-26}" width="100" height="52"/><text class="node-label" x="${n.x+shift}" y="${n.y-5}">${esc(n.type)}</text>${n.value?`<text class="node-sub" x="${n.x+shift}" y="${n.y+13}">${esc(n.value)}</text>`:''}</g>`).join('');return `<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${lines}${ns}</svg>`}
function automataSvg(d,subset){if(!d?.states)return '<div class="empty">No states.</div>';const n=d.states,cols=n<=6?n:Math.ceil(Math.sqrt(n)),rows=Math.ceil(n/cols),w=Math.max(900,cols*175+120),h=Math.max(350,rows*165+130),nodes=Array.from({length:n},(_,i)=>({x:90+(i%cols)*175,y:82+Math.floor(i/cols)*165}));const groups={};(d.transitions||[]).forEach(t=>{const k=t.from+'-'+t.to;(groups[k]??=[]).push(t.symbol)});const marker='m'+Math.random().toString(36).slice(2);const defs=`<defs><marker id="${marker}" markerWidth="10" markerHeight="10" refX="8" refY="3.5" orient="auto"><path d="M0,0 L0,7 L9,3.5 z" fill="#49769f"/></marker></defs>`;const edges=Object.entries(groups).map(([k,syms])=>{const [a,b]=k.split('-').map(Number),A=nodes[a],B=nodes[b],label=esc(syms.join(', '));if(a===b)return `<path class="edge graph-edge" marker-end="url(#${marker})" d="M${A.x} ${A.y-31} C${A.x-58} ${A.y-110},${A.x+58} ${A.y-110},${A.x} ${A.y-31}"/><text class="edge-label" x="${A.x}" y="${A.y-95}" text-anchor="middle">${label}</text>`;const same=A.y===B.y;const mx=(A.x+B.x)/2,my=(A.y+B.y)/2+(same?(a<b?-52:52):0);const dpath=same?`M${A.x} ${A.y} Q${mx} ${my} ${B.x} ${B.y}`:`M${A.x} ${A.y} Q${mx+(a>b?42:-42)} ${my} ${B.x} ${B.y}`;return `<path class="edge graph-edge" marker-end="url(#${marker})" d="${dpath}"/><text class="edge-label" x="${mx}" y="${my-9}" text-anchor="middle">${label}</text>`}).join('');const start=nodes[d.start||0];const startArrow=`<path class="start-arrow" marker-end="url(#${marker})" d="M${start.x-68} ${start.y} L${start.x-34} ${start.y}"/>`;const ns=nodes.map((p,i)=>{const acc=isAccepting(d,i),subsetText=subset&&d.subsets?.[i];return `<g class="state-node" data-state="${i}" tabindex="0"><circle class="state ${i===d.start?'start ':''}${acc?'accept':''}" cx="${p.x}" cy="${p.y}" r="34"/>${acc?`<circle class="accept-ring" cx="${p.x}" cy="${p.y}" r="27"/>`:''}<text class="node-label" x="${p.x}" y="${p.y+5}">q${i}</text>${subsetText?`<text class="node-sub" x="${p.x}" y="${p.y+56}">{${subsetText.join(', ')}}</text>`:''}</g>`}).join('');return `<svg class="automata-svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${defs}${startArrow}${edges}${ns}</svg>`}
function bindGraphs(){['nfa','dfa','minimized'].forEach(id=>document.querySelectorAll(`#${id} .state-node`).forEach(node=>{node.addEventListener('click',()=>inspectState(id,node));node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')inspectState(id,node)});}));document.querySelectorAll('#ast .ast-node-wrap').forEach(node=>node.addEventListener('click',()=>{const n=node.dataset.node,ins=$('astInspector');ins.innerHTML=`<b>AST NODE ${esc(n)}</b><span>SYNTAX TREE</span><p>Selected parser node. This intermediate representation is consumed by Thompson construction.</p>`;ins.classList.remove('hidden')}));}
function inspectState(stage,node){document.querySelectorAll(`#${stage} .state-node`).forEach(n=>n.classList.remove('selected'));node.classList.add('selected');const d=stage==='nfa'?compiled?.nfa:stage==='dfa'?compiled?.dfa:compiled?.minimized;if(!d)return;const i=Number(node.dataset.state),out=(d.transitions||[]).filter(t=>t.from===i).map(t=>`${esc(t.symbol)} → q${t.to}`).join('<br>')||'no outgoing transitions';const ins=$(stage+'Inspector');ins.innerHTML=`<b>STATE q${i}</b><span>${isAccepting(d,i)?'ACCEPTING':'NON-ACCEPTING'}${i===d.start?' · START':''}</span><p>${d.subsets?.[i]?`subset: {${d.subsets[i].join(', ')}}<br>`:''}${out}</p>`;ins.classList.remove('hidden');}
$('testBtn').onclick=testString;$('testString').onkeydown=e=>{if(e.key==='Enter')testString()};
async function testString(){if(!compiled){$('matchResult').className='result idle';$('matchResult').textContent='Compile a regex first.';return}try{$('replayStatus').textContent='RUNNING';$('replayStatus').parentElement.classList.add('active');const r=await fetch('/api/match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({regex:compiled.regex,string:$('testString').value})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Match failed.');$('matchResult').className='result '+(d.accepted?'accept':'reject');$('matchResult').innerHTML=d.accepted?'✓ ACCEPTED':'✕ REJECTED';$('pathView').innerHTML=`<div class="path-title">STATE TRAVERSAL</div><div class="path-row">${d.path.map((x,i)=>`<span class="path-state">q${x}</span>${i<d.path.length-1?'<b>→</b>':''}`).join('')}</div>${d.message?`<div class="path-message">${esc(d.message)}</div>`:''}<div class="execution-table"><h3>EXECUTION TRACE</h3><table class="data-table"><thead><tr><th>STEP</th><th>INPUT</th><th>FROM</th><th>TO</th><th>STATUS</th></tr></thead><tbody>${(d.steps||[]).map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.symbol)}</td><td>q${s.from}</td><td>${s.to>=0?'q'+s.to:'—'}</td><td>${s.transitionFound?'✓':'✕'}</td></tr>`).join('')}</tbody></table></div>`;animateReplay(d.steps||[]);showStage('testing')}catch(e){$('replayStatus').textContent='ERROR';$('matchResult').className='result reject';$('matchResult').textContent=e.message}}
function animateReplay(steps){clearInterval(replayTimer);replaySteps=steps||[];replayIndex=-1;const track=$('replayTrack');track.innerHTML=replaySteps.length?replaySteps.map((s,i)=>`<div class="replay-step"><small>${i+1}</small><b>q${s.from}</b><span>${esc(s.symbol)}</span><b>${s.to>=0?'q'+s.to:'—'}</b></div>`).join(''):'<span class="console-dim">No transitions.</span>';replayTimer=setInterval(()=>{replayIndex++;paintReplay();if(replayIndex>=replaySteps.length-1){clearInterval(replayTimer);$('replayStatus').textContent='COMPLETE'}},500)}
function paintReplay(){document.querySelectorAll('.replay-step').forEach((x,i)=>x.classList.toggle('current',i===replayIndex));if(replaySteps.length)$('replayStatus').textContent=replayIndex<0?'READY':`STEP ${Math.min(replayIndex+1,replaySteps.length)}/${replaySteps.length}`;}
$('stepBtn').onclick=()=>{clearInterval(replayTimer);if(replaySteps.length){replayIndex=Math.min(replayIndex+1,replaySteps.length-1);paintReplay()}};$('resetRun').onclick=resetRun;
function resetRun(){$('testString').value='';$('matchResult').className='result idle';$('matchResult').textContent=compiled?'Ready for execution.':'Compile a regex first.';$('pathView').innerHTML='';clearInterval(replayTimer);replaySteps=[];replayIndex=-1;$('replayTrack').innerHTML='<span class="console-dim">Run an input to generate the execution timeline.</span>';$('replayStatus').textContent='IDLE';$('replayStatus').parentElement.classList.remove('active')}
$('nfaAnimate').onclick=()=>document.querySelectorAll('#nfaView .state-node').forEach((n,i)=>{n.classList.remove('build');setTimeout(()=>n.classList.add('build'),i*75)});
document.querySelectorAll('.graph-tools button').forEach(b=>b.onclick=()=>{const stage=b.closest('.stage').id;if(b.dataset.zoom==='in')graphScale=Math.min(1.7,graphScale+.1);else if(b.dataset.zoom==='out')graphScale=Math.max(.6,graphScale-.1);else if(b.dataset.zoom==='reset')graphScale=1;applyGraphZoom(stage)});
$('copyJsonBtn').onclick=async()=>{if(!compiled)return showError('Build a regex first.');await navigator.clipboard?.writeText(JSON.stringify(compiled,null,2));flash($('copyJsonBtn'),'COPIED')};
$('clearLog').onclick=()=>{$('compilerLog').innerHTML='<div class="console-dim">$ console cleared</div>'};
function flash(btn,text){const old=btn.textContent;btn.textContent=text;setTimeout(()=>btn.textContent=old,900)}
function logCompiler(lines){$('compilerLog').innerHTML=lines.map((x,i)=>`<div class="logline" style="--d:${i*55}ms"><span>${String(i+1).padStart(2,'0')}</span>${esc(x)}</div>`).join('')}
function saveHistory(regex){let h=JSON.parse(localStorage.getItem('regexForgeHistory')||'[]');h=[regex,...h.filter(x=>x!==regex)].slice(0,8);localStorage.setItem('regexForgeHistory',JSON.stringify(h))}
function openHistory(){const h=JSON.parse(localStorage.getItem('regexForgeHistory')||'[]');$('historyList').innerHTML=h.length?h.map(r=>`<div class="history-item" data-regex="${esc(r)}"><code>${esc(r)}</code><small>LOAD →</small></div>`).join(''):'<div class="empty">No saved builds yet.</div>';document.querySelectorAll('.history-item').forEach(x=>x.onclick=()=>{$('regex').value=x.dataset.regex;closeModals();compile()});openModal('historyModal')}
function openModal(id){$(id)?.classList.remove('hidden')}function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'))}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));$('historyBtn').onclick=openHistory;$('shortcutsBtn').onclick=()=>openModal('shortcutModal');$('footerHelp').onclick=()=>openModal('shortcutModal');
const commands=[['⌘','Build current regex','Ctrl Enter'],['01','Open Lexer','1'],['02','Open Parser / AST','2'],['03','Open Thompson NFA','3'],['04','Open Subset DFA','4'],['05','Open Minimization','5'],['06','Open Execution','7'],['08','Open Toolbox','8'],['↺','Recent builds',''],['◈','Presentation mode','']];
function renderCommands(filter=''){const list=commands.filter(c=>c[1].toLowerCase().includes(filter.toLowerCase()));$('commandList').innerHTML=list.map((c,i)=>`<div class="command-item" data-cmd="${i}"><span>${c[0]}</span><b>${c[1]}</b><small>${c[2]}</small></div>`).join('');document.querySelectorAll('.command-item').forEach(x=>x.onclick=()=>runCommand(Number(x.dataset.cmd)))}
function runCommand(i){closeModals();const c=commands[i][1];if(c.startsWith('Build'))compile();else if(c==='Recent builds')openHistory();else if(c.startsWith('Presentation'))togglePresentation();else if(c.startsWith('Open')){const map={'Open Lexer':'tokens','Open Parser / AST':'ast','Open Thompson NFA':'nfa','Open Subset DFA':'dfa','Open Minimization':'minimized','Open Execution':'testing','Open Toolbox':'lab'};showStage(map[c])}}
$('commandSearch').oninput=e=>renderCommands(e.target.value);$('commandBtn').onclick=()=>{openModal('commandModal');renderCommands();$('commandSearch').focus()};renderCommands();
$('presentationBtn').onclick=togglePresentation;function togglePresentation(){presentation=!presentation;document.body.classList.toggle('presentation',presentation);$('presentationBtn').textContent=presentation?'Exit presentation':'◈ Presentation'}
$('saveSnapshotBtn').onclick=()=>{if(!compiled)return showError('Build a regex first.');saveHistory(compiled.regex);flash($('saveSnapshotBtn'),'SAVED')};

// ========================= TOOLBOX =========================
function updateAnalysis(){if(!compiled)return;const r=compiled.regex,s=compiled.stats;let depth=0,maxDepth=0,ops=0,classes=0;for(let i=0;i<r.length;i++){const c=r[i];if(c==='\\'){i++;continue}if(c==='('){depth++;maxDepth=Math.max(maxDepth,depth);ops++}else if(c===')'){depth--}else if('|*+?'.includes(c)){ops++}else if(c==='['){classes++}}const growth=s.nfaStates?((s.dfaStates/s.nfaStates)*100):0;const reduction=s.dfaStates?((1-s.minimizedStates/s.dfaStates)*100):0;const score=Math.min(99,Math.round(r.length*1.7+ops*5+maxDepth*8+s.alphabet*3));$('analysisTitle').textContent=r;$('analysisSummary').textContent=`The current source expands into ${s.nfaStates} NFA states, ${s.dfaStates} DFA states and ${s.minimizedStates} minimized states.`;$('complexityScore').textContent=score+'/100';$('aLength').textContent=r.length;$('aOperators').textContent=ops;$('aDepth').textContent=maxDepth;$('aAlphabet').textContent=s.alphabet;$('aGrowth').textContent=growth.toFixed(0)+'%';$('aReduction').textContent=reduction.toFixed(1)+'%';$('analysisDetails').innerHTML=`<div><span>SOURCE</span><b>${esc(r)}</b></div><div><span>OPERATOR MIX</span><b>${ops} operators${classes?` · ${classes} character class${classes>1?'es':''}`:''}</b></div><div><span>AUTOMATA</span><b>${s.nfaTransitions} NFA transitions · ${s.dfaTransitions} DFA transitions</b></div><div><span>OPTIMIZATION</span><b>${s.dfaStates - s.minimizedStates} DFA state${s.dfaStates-s.minimizedStates===1?'':'s'} removed</b></div>`}
async function compileOnly(regex){const r=await fetch('/api/compile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({regex})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Compilation failed.');return d}
function transitionMap(d){const m=new Map();for(const t of d.transitions||[])m.set(`${t.from}|${t.symbol}`,t.to);return m}
function productEquivalence(a,b){const alpha=[...new Set([...(a.alphabet||[]),...(b.alphabet||[])])].sort();const q=[[a.start,b.start,'']];const seen=new Set([`${a.start},${b.start}`]);const ma=transitionMap(a),mb=transitionMap(b);while(q.length){const [x,y,word]=q.shift();if(isAccepting(a,x)!==isAccepting(b,y))return {equal:false,counterexample:word};for(const c of alpha){const nx=ma.get(`${x}|${c}`);const ny=mb.get(`${y}|${c}`);const key=`${nx??-1},${ny??-1}`;if(!seen.has(key)){seen.add(key);q.push([nx??-1,ny??-1,word+c]);}}}return {equal:true,counterexample:null}}
$('equivBtn').onclick=async()=>{const A=$('equivA').value,B=$('equivB').value;if(!A||!B)return;const out=$('equivResult');out.className='tool-result loading';out.textContent='Compiling both expressions and comparing product states…';try{const [a,b]=await Promise.all([compileOnly(A),compileOnly(B)]);const eq=productEquivalence(a.minimized,b.minimized);out.className='tool-result '+(eq.equal?'success':'failure');out.innerHTML=eq.equal?'<strong>✓ EQUIVALENT</strong><span>Both minimized DFAs recognize the same language.</span>':`<strong>✕ NOT EQUIVALENT</strong><span>Counterexample: <code>${esc(eq.counterexample||'ε')}</code></span>`;$('equivStats').innerHTML=`<div><span>A</span><b>${a.stats.minimizedStates} states</b></div><div><span>B</span><b>${b.stats.minimizedStates} states</b></div><div><span>PRODUCT VISIT</span><b>language comparison</b></div>`}catch(e){out.className='tool-result failure';out.textContent=e.message}}
function allStrings(alpha,maxLen){const result=[''];let frontier=[''];for(let len=1;len<=maxLen;len++){const next=[];for(const pre of frontier)for(const c of alpha){const s=pre+c;next.push(s);result.push(s)}frontier=next}return result}
$('exploreBtn').onclick=async()=>{if(!compiled){$('explorerSummary').textContent='Compile a regex first.';return}const max=Number($('exploreLength').value),alpha=compiled.minimized.alphabet||[];if(!alpha.length){$('explorerSummary').textContent='Alphabet is empty. Only ε is available.';$('explorerResults').innerHTML='<div class="string-chip accepted"><code>ε</code><span>ACCEPT</span></div>';return}const strings=allStrings(alpha.slice(0,4),max);$('explorerSummary').textContent=`Testing ${strings.length} strings over {${alpha.join(', ')}} up to length ${max}.`;try{const r=await fetch('/api/batch-match',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({regex:compiled.regex,strings})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Batch exploration failed.');$('explorerResults').innerHTML=d.results.map(x=>`<div class="string-chip ${x.accepted?'accepted':'rejected'}"><code>${x.string?esc(x.string):'ε'}</code><span>${x.accepted?'✓ ACCEPT':'✕ REJECT'}</span></div>`).join('')}catch(e){$('explorerSummary').textContent=e.message}}
function cppChar(c){if(c==='\\')return "'\\\\'";if(c==="'")return "'\\''";if(c==='\n')return "'\\n'";if(c==='\r')return "'\\r'";if(c==='\t')return "'\\t'";return `'${c}'`}
function generateCpp(d,regex){const accepts=new Set(d.accept||[]);const by={};for(const t of d.transitions||[]){(by[t.from]??=[]).push(t)}let code=`// Generated by Regex Forge\n// Source regex: ${regex.replace(/\n/g,' ')}\n// Target: minimized DFA matcher\n#include <string>\n\nbool matchRegex(const std::string& input) {\n    int state = ${d.start};\n\n    for (char c : input) {\n        switch (state) {\n`;
for(let i=0;i<d.states;i++){code+=`            case ${i}:\n`;const ts=by[i]||[];if(!ts.length){code+='                return false;\n';continue}code+='                switch (c) {\n';for(const t of ts)code+=`                    case ${cppChar(t.symbol)}: state = ${t.to}; break;\n`;code+='                    default: return false;\n                }\n                break;\n'}code+='            default: return false;\n        }\n    }\n\n';if(accepts.size){code+=`    return `+([...accepts].map(x=>`state == ${x}`).join(' || '))+`;\n}\n`; }else code+='    return false;\n}\n';return code}
$('codegenBtn').onclick=()=>{if(!compiled){$('generatedCode').textContent='// Build a regex to generate target code.';return}$('generatedCode').textContent=generateCpp(compiled.minimized,compiled.regex);flash($('codegenBtn'),'READY')};
$('copyCodeBtn').onclick=async()=>{const text=$('generatedCode').textContent;if(!text||text.startsWith('// Build'))return;await navigator.clipboard?.writeText(text);flash($('copyCodeBtn'),'COPIED')};
$('benchmarkBtn').onclick=async()=>{if(!compiled){$('benchmarkResult').innerHTML='<div><span>STATUS</span><b>BUILD FIRST</b></div>';return}const runs=Number($('benchRuns').value),times=[];$('benchmarkBtn').disabled=true;$('benchmarkBtn').textContent='RUNNING…';try{for(let i=0;i<runs;i++){const t=performance.now();await compileOnly(compiled.regex);times.push(performance.now()-t)}const min=Math.min(...times),max=Math.max(...times),avg=times.reduce((a,b)=>a+b,0)/times.length;$('benchmarkResult').innerHTML=`<div><span>MIN</span><b>${min.toFixed(1)} ms</b></div><div><span>AVERAGE</span><b>${avg.toFixed(1)} ms</b></div><div><span>MAX</span><b>${max.toFixed(1)} ms</b></div><div><span>RUNS</span><b>${runs}</b></div>`;$('benchmarkBars').innerHTML=times.map((t,i)=>`<div class="bench-bar" style="--h:${Math.max(12,Math.min(100,t/max*100))}%"><span>${i+1}</span><b>${t.toFixed(1)}</b></div>`).join('')}catch(e){$('benchmarkResult').innerHTML=`<div class="bench-error">${esc(e.message)}</div>`}finally{$('benchmarkBtn').disabled=false;$('benchmarkBtn').textContent='BENCHMARK'}};
$('exportBtn').onclick=()=>{if(!compiled)return showError('Build a regex first.');const active=['nfa','dfa','minimized'].find(id=>document.querySelector(`#${id}.active`))||'minimized';const svg=$(active+'View')?.querySelector('svg');if(!svg)return showError('Open an automaton stage first.');const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`regex-${active}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
